/// Flutter icons Google
/// Copyright (C) 2022 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  Google
///      fonts:
///       - asset: fonts/Google.ttf
///
/// 
///
import 'package:flutter/widgets.dart';

class Google {
  Google._();

  static const _kFontFam = 'Google';
  static const String _kFontPkg = null;

  static const IconData google = IconData(0xe802, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
