/// Flutter icons Twitter
/// Copyright (C) 2022 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  Twitter
///      fonts:
///       - asset: fonts/Twitter.ttf
///
///
///
import 'package:flutter/widgets.dart';

class Twitter {
  Twitter._();

  static const _kFontFam = 'Twitter';
  static const String _kFontPkg = null;
  static const IconData twitter = IconData(0xe801, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
